//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place bid.
        /// </summary>
        internal static string AddBid {
            get {
                return ResourceManager.GetString("AddBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin dashboard.
        /// </summary>
        internal static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string Analytics {
            get {
                return ResourceManager.GetString("Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to authenticate. Verify your apikey passed in request header..
        /// </summary>
        internal static string ApiAuthError {
            get {
                return ResourceManager.GetString("ApiAuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has assigned api key.
        /// </summary>
        internal static string ApiKeyExist {
            get {
                return ResourceManager.GetString("ApiKeyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction is ended.
        /// </summary>
        internal static string AuctionEnded {
            get {
                return ResourceManager.GetString("AuctionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction is not published yet.
        /// </summary>
        internal static string AuctionIsDraft {
            get {
                return ResourceManager.GetString("AuctionIsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t bid on your own auction.
        /// </summary>
        internal static string BidInvalidUser {
            get {
                return ResourceManager.GetString("BidInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid value is invalid.
        /// </summary>
        internal static string BidInvalidValue {
            get {
                return ResourceManager.GetString("BidInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid has been successfully added.
        /// </summary>
        internal static string BidPlaced {
            get {
                return ResourceManager.GetString("BidPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bids.
        /// </summary>
        internal static string Bids {
            get {
                return ResourceManager.GetString("Bids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid value is too low.
        /// </summary>
        internal static string BidToLow {
            get {
                return ResourceManager.GetString("BidToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business report.
        /// </summary>
        internal static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid.
        /// </summary>
        internal static string CreateBid {
            get {
                return ResourceManager.GetString("CreateBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New auctions.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>

        ///   Looks up a localized string similar to Edit auction.
        /// </summary>
        internal static string EditAuction {
            get {
                return ResourceManager.GetString("EditAuction", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Auctions ended.
        /// </summary>
        internal static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);

            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end in.
        /// </summary>
        internal static string EndIn {
            get {
                return ResourceManager.GetString("EndIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too long input.
        /// </summary>
        internal static string FieldTooLong {
            get {
                return ResourceManager.GetString("FieldTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too short input.
        /// </summary>
        internal static string FieldTooShort {
            get {
                return ResourceManager.GetString("FieldTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new api key.
        /// </summary>
        internal static string GenerateApiKey {
            get {
                return ResourceManager.GetString("GenerateApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        internal static string HighContrast {
            get {
                return ResourceManager.GetString("HighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer format is invalid.
        /// </summary>
        internal static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question format is invalid.
        /// </summary>
        internal static string InvalidQuestion {
            get {
                return ResourceManager.GetString("InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request data was invalid.
        /// </summary>
        internal static string InvalidRequestData {
            get {
                return ResourceManager.GetString("InvalidRequestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as .
        /// </summary>
        internal static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message has been sent.
        /// </summary>
        internal static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>

        ///   Looks up a localized string similar to My auctions.
        /// </summary>
        internal static string MyAuctions {
            get {
                return ResourceManager.GetString("MyAuctions", resourceCulture);
            }
        }    
  
        ///   Looks up a localized string similar to Auctions history csv.
        /// </summary>
        internal static string MyAuctionsCsv {
            get {
                return ResourceManager.GetString("MyAuctionsCsv", resourceCulture);
            }
        }
        
        /// <summary>

        ///   Looks up a localized string similar to My Bids.
        /// </summary>
        internal static string MyBids {
            get {
                return ResourceManager.GetString("MyBids", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Auctions history pdf.
        /// </summary>
        internal static string MyAuctionsPdf {
            get {
                return ResourceManager.GetString("MyAuctionsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your answer here....
        /// </summary>
        internal static string NewAnswer {
            get {
                return ResourceManager.GetString("NewAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save it in safe place. Your api key is.
        /// </summary>
        internal static string NewApiKey {
            get {
                return ResourceManager.GetString("NewApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask your question to seller here.....
        /// </summary>
        internal static string NewQuestion {
            get {
                return ResourceManager.GetString("NewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bid value found in request body.
        /// </summary>
        internal static string NoBidValue {
            get {
                return ResourceManager.GetString("NoBidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result.
        /// </summary>
        internal static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to do this.
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not owner.
        /// </summary>
        internal static string NotOwner {
            get {
                return ResourceManager.GetString("NotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You now observe auction: .
        /// </summary>
        internal static string NowObserving {
            get {
                return ResourceManager.GetString("NowObserving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observed.
        /// </summary>
        internal static string Observed {
            get {
                return ResourceManager.GetString("Observed", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Categories popularity.
        /// </summary>
        internal static string Popularity {
            get {
                return ResourceManager.GetString("Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string PriceFrom {
            get {
                return ResourceManager.GetString("PriceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string PriceTo {
            get {
                return ResourceManager.GetString("PriceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Active.
        /// </summary>
        internal static string ShowActive {
            get {
                return ResourceManager.GetString("ShowActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Draft.
        /// </summary>
        internal static string ShowDraft {
            get {
                return ResourceManager.GetString("ShowDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Ended.
        /// </summary>
        internal static string ShowEnded {
            get {
                return ResourceManager.GetString("ShowEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        internal static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
          }
        }
        ///   Looks up a localized string similar to Report time span (days).
        /// </summary>
        internal static string TimeSpan {
            get {
                return ResourceManager.GetString("TimeSpan", resourceCulture);
            }
        }
    }
}
